import Head from 'next/head'
import Image from 'next/image'
import HomePage from '../components/HomePage'



export default function Home({data}) {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://api.fontshare.com/v2/css?f[]=clash-display@200,400,700,500,600,300&display=swap" rel="stylesheet"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <header>
      <nav className='flex justify-center items-center text-3xl gap-10 my-10'>
        <img src="" alt="" />
        <a href="/">Home</a>
        <a href="/events">Events</a>
        <a href="/aboutus">About Us</a>
      </nav>
    </header>
   <HomePage data={data}/>

    </div>
  )
}
export async function getServerSideProps(){
const {events_categories}= await import('/data/data.json')

  return{
    props:{
     data: events_categories
    }
  }
}
