import Head from 'next/head'



export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://api.fontshare.com/v2/css?f[]=clash-display@200,400,700,500,600,300&display=swap" rel="stylesheet"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <header>
      <nav className='flex justify-center items-center text-3xl gap-10 my-10'>
        <img src="" alt="" />
        <a href="/">Home</a>
        <a href="/events">Events</a>
        <a href="/aboutus">About Us</a>
      </nav>
    </header>
    <main>
      <a href=''>
        <h2 className='text-3xl font-semibold'>events in london</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae reiciendis laboriosam minima, aspernatur molestias nulla esse impedit neque doloremque ex? Non sit consequuntur, et placeat libero dignissimos temporibus eos corrupti iste suscipit autem ipsam officia voluptatum quisquam laboriosam neque quas quasi nesciunt. Officia, neque, sint molestias quam at exercitationem ab consectetur sequi itaque provident incidunt laboriosam aspernatur porro deleniti quaerat doloremque tempore eum commodi aliquam harum perspiciatis optio corrupti nam. Aperiam veritatis eum nostrum doloribus minima deserunt impedit molestias libero esse magnam. Ipsa magnam non fugiat sunt voluptas aspernatur voluptatem facilis omnis dolores nostrum nesciunt, quos inventore vel beatae dolor repudiandae doloribus accusamus voluptate odio eos. Tenetur voluptatum sequi repellendus, hic quia commodi illum fugit deleniti. Eum, porro numquam facere soluta quod reprehenderit maxime sit ipsa perferendis et eos. Amet explicabo sapiente voluptatem facilis debitis eligendi eaque nemo alias quos natus aspernatur perferendis repellat eos, nobis ut quaerat quisquam omnis nisi illum quo beatae nam est? Assumenda earum dicta neque cupiditate recusandae mollitia voluptatum minus reiciendis? In consequatur eaque ducimus maiores, suscipit non cupiditate voluptatem facilis delectus! Dolor facilis illo voluptatibus nemo exercitationem maiores quo aliquam incidunt. Voluptates temporibus officia, harum tempora tempore assumenda ea asperiores omnis ut dicta consectetur!</p>
      </a>
    </main>

    </div>
  )
}
